# preload = ~/.config/backgrounds/shaded.png
# wallpaper = , ~/.config/backgrounds/shaded.png

# preload = ~/Pictures/wallpaper/wallpapers/Sun-Setting-Horizon.png
# wallpaper = , ~/Pictures/wallpaper/wallpapers/Sun-Setting-Horizon.png

# You must preload the file first
# preload = /home/prashanth/Pictures/wallpaper/wallpapers/Sun-Setting-Horizon.png

# Assign to your specific monitor
wallpaper {
    monitor = 
    # path = ~/Pictures/wallpaper/wallpapers/
    # path = /home/prashanth/Pictures/wallpaper/wallpapers/Sun-Setting-Horizon.png
    path = /home/prashanth/Pictures/wallpaper/wallpapers/River.png
    order = random
    fit_mode = cover
}

# Optional: Disable the splash text
splash = false
 
